### ISSUE TITLE
Unable to register/sign-up/login

### ISSUE THREAD

**Issue by TurtleEggs** [realm-demos/realm-tasks#422]
Hello there, i have a problem logging in, the following is what i've done so far,

- Installed ROS on a Ubuntu within a guest VM and set network settings to bridged so it'd be assigned a unique ip address 192.168.1.9 that is within the same LAN as my host machine. I have already configured and registered my ROS and was able to login from the vm as well as my host's web browser so i verified that it capable of internet connectivity/requests. **HOWEVER** after opening the RealmTasks project in Android Studio and running the project - (also i have an actual device LG 15332 connected instead of emulator) - I attempt to register with UN/PW and receive the following output 

`06-06 10:43:06.331 12633-12771/io.realm.realmtasks D/REALM_JAVA: AuthenticateResponse - Error: UNKNOWN(-1)
                                                                 java.net.SocketTimeoutException: failed to connect to /192.168.1.9 (port 9080) after 10000ms
                                                                     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                     at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                     at java.net.Socket.connect(Socket.java:886)
                                                                     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:61)
                                                                     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
                                                                     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
                                                                     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
                                                                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
                                                                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                     at okhttp3.RealCall.execute(RealCall.java:60)
                                                                     at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:111)
                                                                     at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:53)
                                                                     at io.realm.SyncUser.login(SyncUser.java:189)
                                                                     at io.realm.SyncUser$1.run(SyncUser.java:228)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
06-06 10:43:06.331 12633-12771/io.realm.realmtasks I/REALM_JAVA: Failed authenticating user.
                                                                 UNKNOWN(-1)
                                                                 java.net.SocketTimeoutException: failed to connect to /192.168.1.9 (port 9080) after 10000ms
                                                                     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                     at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                     at java.net.Socket.connect(Socket.java:886)
                                                                     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:61)
                                                                     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
                                                                     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
                                                                     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
                                                                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
                                                                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
                                                                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
                                                                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                     at okhttp3.RealCall.execute(RealCall.java:60)
                                                                     at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:111)
                                                                     at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:53)
                                                                     at io.realm.SyncUser.login(SyncUser.java:189)
                                                                     at io.realm.SyncUser$1.run(SyncUser.java:228)
                                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)`

-- I have inserted the correct ip address of my ubuntu 16.04 machine in the RealmTaskApplication.java..

can someone please help me out, I want to follow the realm/doc tutorials so i can learn and implement realm in future projects but I cant figure out why my connection is timing out. Thank you guys

**Comment by evatheodoridoubjss** [comment]
Did you ever get a solution to this?

I am trying to login a user to a synced realm and get this error:

`error while executing job com.bjss.bjssevents.jobs.LoginUserToSyncedRealmJob@29e446e
      UNKNOWN(-1)
      java.net.SocketTimeoutException: connect timed out
            at java.net.PlainSocketImpl.socketConnect(Native Method)
            at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
            at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
            at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
            at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
            at java.net.Socket.connect(Socket.java:586)
            at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:221)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
            at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
            at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
            at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
            at okhttp3.RealCall.execute(RealCall.java:69)
            at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:146)
            at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:54)
            at io.realm.SyncUser.login(SyncUser.java:195)
            at com.bjss.bjssevents.jobs.LoginUserToSyncedRealmJob.onRun(LoginUserToSyncedRealmJob.java:35)     < ---  My class
            at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
            at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
            at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
            at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
           at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
           at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
           at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
           at java.lang.Thread.run(Thread.java:762)
                                                               
           at io.realm.internal.network.AuthenticateResponse.from(AuthenticateResponse.java:82)
           at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:56)
           at io.realm.SyncUser.login(SyncUser.java:195)
           at com.bjss.bjssevents.jobs.LoginUserToSyncedRealmJob.onRun(LoginUserToSyncedRealmJob.java:35)
           at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
           at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
           at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
           at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
           at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
           at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)`
