### ISSUE TITLE
Crash when upgrading to 3.5.0 / 2.1.0 (adapters)

### ISSUE THREAD

**Issue by ericmaxwell2003** [realm-demos/realm-tasks#423]
Steps to reproduce:

1. Upgrade to the latest versions (3.5.0 Realm, 2.1.0 Realm Adapter)
2. Update `CommonAdapter` to store the context off, instead of passing up to the RealmRecyclerView.   Something like the following.  (not recommending this, but it's the easiest route to refactor so you can still compile/build the project and reproduce the issue.
    
```
    public Context context;

    public CommonAdapter(Context context, OrderedRealmCollection<T> items) {
        super(items, true); this.context = context;
    }

```

3.  Run the app, register, login, and add a new Task, by dragging down on the task list.
4.  App will crash with this stacktrace

`08-01 08:50:42.680 16801-16801/io.realm.realmtasks E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: io.realm.realmtasks, PID: 16801
                                                                     java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1b02ec0 position=8 id=-1, oldPos=6, pLpos:6 scrap [attachedScrap] tmpDetached no parent}
                                                                         at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by dalinaum** [comment]
Since notifications are changed so much, `adapter.notifyXXXX` should be removed like #405
But there are visual artifacts and it should be investigated.

**Comment by Zhuinden** [comment]
Keep the notifyDataSetChanged() calls, but remove all notifyItem* calls.

**Comment by Zhuinden** [comment]
Should be fixed by https://github.com/realm-demos/realm-tasks/pull/428
